# Generated by Django 5.2.13 on 2026-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_gamereward_delete_scratchcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereward',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
