# Generated by Django 5.2.13 on 2026-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0006_transaction_account_holder_transaction_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
